name: Phonebook Deployment Pipeline

permissions:
  contents: write

on:
  push:
    branches: main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  ON_MAIN_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  SKIP_RELEASE: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ------------------------------------------------------------------------
      #                                 Frontend
      # ------------------------------------------------------------------------
      - name: Install frontend dependencies
        working-directory: phonebook-ci-cd/frontend
        run: npm install

      - name: Lint frontend
        working-directory: phonebook-ci-cd/frontend
        run: npm run lint

      - name: Build frontend
        working-directory: phonebook-ci-cd/frontend
        run: npm run build

      # ------------------------------------------------------------------------
      #                                 Backend
      # ------------------------------------------------------------------------
      - name: Install backend dependencies
        working-directory: phonebook-ci-cd/backend
        run: npm install

      - name: Lint backend
        working-directory: phonebook-ci-cd/backend
        run: npm run lint

      # ------------------------------------------------------------------------
      #                                 Deploy
      # ------------------------------------------------------------------------
      - name: Deploy to render
        if: env.ON_MAIN_PUSH == 'true' && env.SKIP_RELEASE == 'false'
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          wait_deploy: true

      # ------------------------------------------------------------------------
      #                                 Failure notification
      # ------------------------------------------------------------------------
      - name: Notify Discord on failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: CI Bot
          avatarUrl: https://i.imgur.com/4M34hi2.png
          severity: error
          title: "Build failed"
          description: "Commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }}"
          footer: "Severity: Error"

  tag_release:
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        if: env.ON_MAIN_PUSH == 'true' && env.SKIP_RELEASE == 'false'
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Notify Discord on success
        if: success()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: CI Bot
          avatarUrl: https://i.imgur.com/4M34hi2.png
          severity: info
          title: "A new version of Phonebook deployed"
          description: "Version **${{ steps.tag.outputs.new_tag }}** deployed to <https://fso-ci-cd-0q26.onrender.com/> by ${{ github.actor }}"
          footer: "Severity: Informational"

      - name: Notify Discord on failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: CI Bot
          avatarUrl: https://i.imgur.com/4M34hi2.png
          severity: error
          title: "Tagging failed"
          description: "Commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }}"
          footer: "Severity: Error"
